version: '3'
services:
  mongodb:
    image: mongo
    command: "mongod --noauth --bind_ip=0.0.0.0"
    # volumes:
    #   - c:/Users/mi.sokoluk/data/:/data/db
    volumes:
      - mongodata:/data/db
    ports:
        - 27017:27017
    container_name: quest_db

volumes:
  mongodata:
